name: receive-all
on:
    schedule:
        - cron: "* 0 * * *"
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: Call our API route to receive all
              run: |
                  curl --request POST 'https://nano-testnet-faucet.vercel.app/api/receiveAll'
